add likes to the article
asb29/Redwing pull request #18
Opened 2016-10-02 17:12 UTC by meikuam

add backend code for likes (tricks)

2016-10-02 17:16 UTC, asb29 commented on news/models.py
> +
too many lines

2016-10-02 17:17 UTC, asb29 commented on news/templates/news/article_detail.html
> +				<p>This artickle habe {{likes}} tricks</p>
need spaces around variable, like {{ likes }}

2016-10-02 17:17 UTC, asb29 commented on news/templates/news/article_detail.html
> +				<p>{{liked}}</p>
spaces here too

2016-10-02 17:18 UTC, asb29 commented on news/templates/news/article_detail.html
> +				<form action="like" method="POST">
better change action to  django's {% url %} (check other template files for examples)

2016-10-02 17:18 UTC, asb29 commented on news/views.py
> +		context['likes'] = Like.objects.filter(article=self.object).__len__()
len()

2016-10-02 17:18 UTC, asb29 commented on news/views.py
> +		context['liked'] = 'True' if Like.objects.filter(article=self.object, author=self.request.user).__len__() != 0 else 'False'
len()

2016-10-02 17:19 UTC, asb29 commented on news/views.py
> +	return redirect(article, slug)
add newline at the end of the file

2016-10-02 17:19 UTC, asb29 commented on news/views.py
> +		if like_.__len__() == 0:
len()

2016-10-02 17:19 UTC, asb29 requested changes
fix some minor stuff i pointed in comments

2016-10-02 17:25 UTC, asb29 commented on news/templates/news/article_detail.html
> +				<form action="like" method="POST">
also fix typos line 28

2016-10-02 17:40 UTC, asb29 commented on news/views.py
add login_required decorator, same as in comment view

2016-10-08 17:11 UTC, meikuam commented on news/models.py
> +
lines removed.

2016-10-08 17:11 UTC, meikuam commented on news/templates/news/article_detail.html
> +				<p>This artickle habe {{likes}} tricks</p>
changed in next commit.

2016-10-08 17:12 UTC, meikuam commented on news/templates/news/article_detail.html
> +				<p>{{liked}}</p>
changed this too.

2016-10-09 09:38 UTC, merged